config/routes.rb
Rails.application.routes.draw do
  resources :drivers
  
  namespace :api do
    resources :drivers, defaults: {format: 'json'}
    get '/drivers/assign_to_booking/:booking_id' => 'drivers#assign'
  end
  

end

app/models/driver.rb
class Driver < ActiveRecord::Base
  validates :name, :phone, presence: true
  validates :phone, uniqueness: true
  
  acts_as_mappable default_units: :kms, default_formula: :sphere, distance_field_name: :distance, lat_column_name: :latitude, lng_column_name: :longitude
  
  def self.get_closest_to(latitude, longitude)
    return Driver.closest(:origin => [latitude, longitude]).first
  end
end

app/controllers/api/drivers_controller.rb
class Api::DriversController < ApplicationController
  require 'rest_client'
  
  http_basic_authenticate_with name: "nostra", password: "welcome1"
  before_action :fetch_driver, except: [:index, :create, :assign, :closest_to]
  skip_before_action :verify_authenticity_token
  respond_to :json
  
  BOOKINGS_REST_API_BASE_URL = 'http://localhost:3000/api'
  BOOKINGS_REST_API_USERNAME = 'nostra'
  BOOKINGS_REST_API_PASSWORD = 'welcome1'
  
  def fetch_driver
    @driver = Driver.find(params[:id])
  end
  
  def index
    @drivers = Driver.all
    respond_to do |format|
      format.json {render json: @drivers}
    end
  end

  def show
    respond_to do |format|
      format.json {render json: @driver}
    end
  end

  def create
    @driver = Driver.new(driver_params)
    respond_to do |format|
      if @driver.save
        format.json {render json: @driver, status: :created}
      else
        format.json {render json: @driver.errors, status: :unprocessable_entity}
      end
    end
  end

  def update
    respond_to do |format|
      if @driver.update_attributes(driver_params)
        format.json {head :no_content, status: :ok}
      else
        format.json {render json: @driver.errors, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    respond_to do |format|
      if @driver.destroy
        format.json {head :no_content, status: :ok}
      else
        format.json {render json: @driver.errors, status: :unprocessable_entity}
      end
    end
  end
  
  def assign
    booking = get_booking_detail(params[:booking_id])
    driver = Driver.get_closest_to(booking[:pickup_latitude], booking[:pickup_longitude])
    respond_with update_driver_in_booking(params[:booking_id], driver.name, driver.phone)
  end
  
  private
  
  def get_booking_detail(booking_id)
    uri = "#{BOOKINGS_REST_API_BASE_URL}/bookings/#{booking_id}"
    rest_resource = RestClient::Resource.new(uri, BOOKINGS_REST_API_USERNAME, BOOKINGS_REST_API_PASSWORD)
    begin
      booking = rest_resource.get
    rescue Exception => e
      booking = {status: "Failed!"}
    end
    return ActiveSupport::JSON.decode(booking)
  end
  
  def update_driver_in_booking(booking_id, name, phone)
    uri = "#{BOOKINGS_REST_API_BASE_URL}/bookings/#{booking_id}"
    rest_resource = RestClient::Resource.new(uri, BOOKINGS_REST_API_USERNAME, BOOKINGS_REST_API_PASSWORD)
    payload = {booking: {driver_name: name, driver_phone: phone}}
    begin
      rest_resource.put payload
      status = {status: "Success!"}
      NotificationWorker.perform_async(name, phone, booking_id)
    rescue Exception => e
      status = {status: "Failed!"}
    end
    return status
  end
  
  def driver_params
    params.require(:driver).permit(:name, :phone, :latitude, :longitude)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  before_action :set_driver, only: [:show, :edit, :update, :destroy]

  # GET /drivers
  # GET /drivers.json
  def index
    @drivers = Driver.all
  end

  # GET /drivers/1
  # GET /drivers/1.json
  def show
  end

  # GET /drivers/new
  def new
    @driver = Driver.new
  end

  # GET /drivers/1/edit
  def edit
  end

  # POST /drivers
  # POST /drivers.json
  def create
    @driver = Driver.new(driver_params)

    respond_to do |format|
      if @driver.save
        format.html { redirect_to @driver, notice: 'Driver was successfully created.' }
        format.json { render :show, status: :created, location: @driver }
      else
        format.html { render :new }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drivers/1
  # PATCH/PUT /drivers/1.json
  def update
    respond_to do |format|
      if @driver.update(driver_params)
        format.html { redirect_to @driver, notice: 'Driver was successfully updated.' }
        format.json { render :show, status: :ok, location: @driver }
      else
        format.html { render :edit }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drivers/1
  # DELETE /drivers/1.json
  def destroy
    @driver.destroy
    respond_to do |format|
      format.html { redirect_to drivers_url, notice: 'Driver was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_driver
      @driver = Driver.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def driver_params
      params.require(:driver).permit(:name, :phone, :latitude, :longitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/views/drivers/_form.html.erb
<%= form_for(@driver) do |f| %>
  <% if @driver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@driver.errors.count, "error") %> prohibited this driver from being saved:</h2>

      <ul>
      <% @driver.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/drivers/edit.html.erb
<h1>Editing driver</h1>

<%= render 'form' %>

<%= link_to 'Show', @driver %> |
<%= link_to 'Back', drivers_path %>

app/views/drivers/index.html.erb
<h1>Listing drivers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @drivers.each do |driver| %>
      <tr>
        <td><%= driver.name %></td>
        <td><%= driver.phone %></td>
        <td><%= driver.latitude %></td>
        <td><%= driver.longitude %></td>
        <td><%= link_to 'Show', driver %></td>
        <td><%= link_to 'Edit', edit_driver_path(driver) %></td>
        <td><%= link_to 'Destroy', driver, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Driver', new_driver_path %>

app/views/drivers/new.html.erb
<h1>New driver</h1>

<%= render 'form' %>

<%= link_to 'Back', drivers_path %>

app/views/drivers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @driver.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @driver.phone %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @driver.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @driver.longitude %>
</p>

<%= link_to 'Edit', edit_driver_path(@driver) %> |
<%= link_to 'Back', drivers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GrabtaxiDispatcher</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>